[project]
name = "hammal"
version = "0.1.0"
description = "A lightweight HTTP router library providing bare minimum routing functionality, designed for easy embedding within other applications."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
